name: React Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy to Server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
      - name: Deploy to Server
        run: ssh server 'cd ${{ secrets.PROJECT_ROOT }} && git fetch && git reset --hard origin/main && cd frontend && rm -rf build/ && npm i && npm run build && sudo rm -rf ${{ secrets.PROJECT_PROD }}* && sudo cp -r build/* ${{ secrets.PROJECT_PROD }} && sudo systemctl restart nginx'
      - name: Test production build
        run: curl https://$SSH_IP/
